### ISSUE TITLE
Add --model, and --list-models option

### ISSUE THREAD

**Issue by divanvisagie** [divanvisagie/chat-gipity#15]
We should be able to switch between [different models offered by OpenAI](https://platform.openai.com/docs/models/how-we-use-your-data) using something like `--model=gpt-4`. If this is implemented it should be  alongside `--list-models` which would list the valid model options.

**Comment by annaleighsmith** [comment]
I'm going to work on this enhancement if that's alright with you :+1:

**Comment by annaleighsmith** [comment]
Just a quick thought on the model option... I think that, along with being able to pass a model, it would be nice to be able to change the default via a configuration file or just an environment variable. That way, you could switch between them, and it would always use your preferred option. Originally, I started with the idea of defaulting to 'gpt-4', but the other way might be more adaptive.

**Comment by divanvisagie** [comment]
Oh... I only saw your feedback request now! I had a quick look and most of it seems logical but will take a deeper dive tonight (EU time).

**Comment by annaleighsmith** [comment]
I like the cgip config ==model=gpt3.5 option as a solution to this. But yeah maybe a separate feature as you said, as of now I implemented with 'gpt-4' as default until that can be added.
