### ISSUE TITLE
Add config subcommand for storing user defined defaults

### ISSUE THREAD

**Issue by divanvisagie** [divanvisagie/chat-gipity#20]
Awesome, thanks for contributing! I was having the same thought about configs, but was thinking of it as a separate feature. If you want though, you can do it in here.

My idea was to have a subcommand similar to how git has `git config`, which would write to a toml file (standard for rust). In the users config directory.

In my opinion the best way to get the path for that directory is to use [this](https://crates.io/crates/dirs) library, as it gets the correct path for whichever operating system you are running on.

So to clarify you would still have a command like `cgip --model=gpt3.5` , plain `cgip` would default to gpt4 or whatever is in the config file, and you could use `cgip config --model=gpt3.5` to set the default. What do you think?

_Originally posted by @divanvisagie in https://github.com/divanvisagie/chat-gipity/issues/15#issuecomment-2097597244_

**Comment by annaleighsmith** [comment]
Going to take this on in the next day or so

**Comment by divanvisagie** [comment]
Awesome, thanks! I have set you ass assignee.
